server:
  port: 9527

netty:
#  host: 172.16.95.6
  host: 192.168.1.6
  port: 8092
mqtt:
  topic: "demo/test"
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.193.195:3306/transoirtion?serverTimezone=Hongkong&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:p6spy:mysql://localhost:3306/transoirtion?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: hanjingwei66
    password: Shuojie,.123456
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    spring.datasource.filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=100
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true


#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#  http:
#    multipart:
#      max-file-size: 200Mb   #文件上传大小
#      max-request-size: 4000Mb  #最打请求大小
#上传位置
uploadDir: F:\mystudy\pic\
#uploadDir: /usr/local/file

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.shuojie.domain
#  configuration:
#    map-underscore-to-camel-case: true

redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
    expire:
      authCode: 3600 # 验证码超期时间
      host: localhost # Redis服务器地址
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
#jedis:
#  pool:
#    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#    max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    max-idle: 8 # 连接池中的最大空闲连接
#    min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 3000ms # 连接超时时间（毫秒）
sensor:
  distanceId: 88853 #超声波
  laserId: 88682  #激光
logging:
  level:
    root: warn
    com.shuojie.dao: debug
  pattern:
    console: '%p%m%n'
